import type { AmdClass } from '@cocally/shared';
import type { PalService } from '../providers/pal.service';
import type { CallRuntime } from './runtime';

export interface SimulationOptions {
  /** Who answers this simulated dial. */
  amdClass?: AmdClass;
  amdLatencyMs?: number;
  /** Scripted customer replies consumed in order (deterministic tests). */
  scriptedReplies?: string[];
  /** Or a persona prompt (PLAT-09 personas: agreeable, hostile, elderly, accented, noisy). */
  personaPrompt?: string;
  /** Result the transfer orchestrator returns; real orchestrator wires in for live calls. */
  transferResult?: 'BRIDGED' | 'NO_AGENT' | 'FAILED';
  onTransferRequest?: (input: { whisperEnabled: boolean; acceptWindowSeconds: number }) => Promise<'BRIDGED' | 'NO_AGENT' | 'FAILED'>;
  tenantId?: string;
  /**
   * When true and a persona is set, the customer's replies are generated by
   * a real configured LLM (varied, genuinely conversational). When false —
   * the correct default with no provider keys configured — replies come
   * from a local deterministic responder instead. Routing the persona
   * through the PAL LLM chain with no real keys would resolve to the same
   * SimulationLlm adapter that plays the AI *agent* role, so both sides of
   * the conversation would be voiced by one canned script and never
   * converge on a qualifying answer.
   */
  preferRealLlmPersona?: boolean;
}

/**
 * Text-mode CallRuntime per FLOW-05: drives a flow against a fake customer
 * with zero telephony. Also the runtime behind TELEPHONY_DRIVER=SIMULATION,
 * where the whole pilot loop (dial → AMD → conversation → transfer) runs
 * in-process.
 */
export class SimulationRuntime implements CallRuntime {
  readonly aiLines: string[] = [];
  readonly customerLines: string[] = [];
  private replyIndex = 0;
  private hungUp = false;
  private lastAiLine = '';
  private personaTurn = 0;
  private readonly personaHistory: Array<{ role: 'system' | 'user' | 'assistant'; content: string }> = [];

  constructor(
    private readonly options: SimulationOptions,
    private readonly pal?: PalService,
  ) {
    if (options.personaPrompt) {
      this.personaHistory.push({
        role: 'system',
        content: `${options.personaPrompt}\nYou are the CUSTOMER on a phone call. Reply with one short natural spoken sentence only.`,
      });
    }
  }

  async say(text: string): Promise<{ bargedIn: boolean }> {
    this.aiLines.push(text);
    this.lastAiLine = text;
    if (this.options.personaPrompt) this.personaHistory.push({ role: 'user', content: text });
    return { bargedIn: false };
  }

  async playAsset(assetId: string): Promise<void> {
    this.aiLines.push(`[audio asset ${assetId}]`);
  }

  async listen(): Promise<string | null> {
    if (this.hungUp) return null;
    if (this.options.scriptedReplies) {
      const reply = this.options.scriptedReplies[this.replyIndex] ?? null;
      this.replyIndex += 1;
      if (reply !== null) this.customerLines.push(reply);
      return reply;
    }
    if (this.options.personaPrompt && this.options.preferRealLlmPersona && this.pal) {
      const completion = await this.pal.llm(
        { tenantId: this.options.tenantId },
        { messages: this.personaHistory, maxTokens: 80, temperature: 0.8 },
      );
      this.personaHistory.push({ role: 'assistant', content: completion.text });
      this.customerLines.push(completion.text);
      return completion.text;
    }
    if (this.options.personaPrompt) {
      const reply = this.deterministicPersonaReply();
      this.personaHistory.push({ role: 'assistant', content: reply });
      this.customerLines.push(reply);
      return reply;
    }
    return null;
  }

  /**
   * Local fake-customer responder used whenever no real LLM key is
   * configured. Reacts to keywords in the AI's last line so the
   * conversation reliably progresses toward qualification without needing
   * an external provider — the flow executor's own SimulationLlm adapter
   * already plays the assistant role, so the customer side must come from
   * somewhere else.
   */
  private deterministicPersonaReply(): string {
    this.personaTurn += 1;
    const lower = this.lastAiLine.toLowerCase();
    if (/don'?t call|do not call|stop calling|remove me/.test(lower)) {
      return "Actually, please don't call me again.";
    }
    if (/own/.test(lower)) {
      return 'Yes, I own my home.';
    }
    if (/bill|quarterly power/.test(lower)) {
      return 'Our quarterly bill runs about $580.';
    }
    if (/visit|specialist|assessment|appointment|time that suits/.test(lower)) {
      return "Yes, that sounds good, let's do that.";
    }
    if (this.personaTurn === 1) {
      return 'Oh hi, who is this?';
    }
    return 'Yeah, sure, go on.';
  }

  async amdClassify(): Promise<{ amdClass: AmdClass; latencyMs: number }> {
    return { amdClass: this.options.amdClass ?? 'HUMAN', latencyMs: this.options.amdLatencyMs ?? 800 };
  }

  async sendDtmf(_digits: string): Promise<void> {
    // No-op in simulation.
  }

  async hangup(): Promise<void> {
    this.hungUp = true;
  }

  async requestTransfer(input: { whisperEnabled: boolean; acceptWindowSeconds: number }): Promise<'BRIDGED' | 'NO_AGENT' | 'FAILED'> {
    if (this.options.onTransferRequest) return this.options.onTransferRequest(input);
    return this.options.transferResult ?? 'NO_AGENT';
  }
}
